import { addDays, startOfWeek, toDateKey, type Appt } from "./constants";

// Dữ liệu mẫu neo vào tuần hiện tại (chỉ số cột 0–5 → ngày thật) để mặc định
// hiển thị ngay ở tuần này; điều hướng qua tuần khác sẽ trống.
const weekAnchor = startOfWeek(new Date());

const rawAppts: Array<Omit<Appt, "date"> & { day: number }> = [
  {
    id: "a1",
    day: 0,
    start: "09:00",
    duration: 45,
    patient: "Hoàng Anh Tú",
    service: "Khám tổng quát",
    status: "done",
  },
  {
    id: "a2",
    day: 0,
    start: "14:00",
    duration: 60,
    patient: "Ngô Bảo Châu",
    service: "Điều trị tủy",
    status: "booked",
  },
  {
    id: "a3",
    day: 1,
    start: "08:30",
    duration: 30,
    patient: "Lý Thu Hằng",
    service: "Cạo vôi răng",
    status: "done",
  },
  {
    id: "a4",
    day: 1,
    start: "10:30",
    duration: 90,
    patient: "Trịnh Văn Sơn",
    service: "Cấy ghép Implant",
    status: "booked",
  },
  {
    id: "a5",
    day: 2,
    start: "08:00",
    duration: 30,
    patient: "Trần Thu Hà",
    service: "Cạo vôi răng",
    status: "done",
  },
  {
    id: "a6",
    day: 2,
    start: "08:30",
    duration: 45,
    patient: "Nguyễn Văn Long",
    service: "Nhổ răng khôn",
    status: "in_progress",
  },
  {
    id: "a7",
    day: 2,
    start: "09:15",
    duration: 45,
    patient: "Lê Minh Châu",
    service: "Trám răng thẩm mỹ",
    status: "arrived",
  },
  {
    id: "a8",
    day: 2,
    start: "10:00",
    duration: 30,
    patient: "Phạm Quốc Bảo",
    service: "Niềng răng — tái khám",
    status: "booked",
  },
  {
    id: "a9",
    day: 2,
    start: "10:45",
    duration: 60,
    patient: "Vũ Thị Mai",
    service: "Tẩy trắng răng",
    status: "booked",
  },
  {
    id: "a10",
    day: 2,
    start: "14:30",
    duration: 90,
    patient: "Đỗ Hoàng Nam",
    service: "Cấy ghép Implant",
    status: "booked",
  },
  {
    id: "a11",
    day: 3,
    start: "09:00",
    duration: 30,
    patient: "Bùi Khánh Vy",
    service: "Khám định kỳ",
    status: "booked",
  },
  {
    id: "a12",
    day: 3,
    start: "11:00",
    duration: 45,
    patient: "Đặng Thu Uyên",
    service: "Trám răng",
    status: "cancelled",
  },
  {
    id: "a13",
    day: 4,
    start: "08:30",
    duration: 60,
    patient: "Phan Đức Minh",
    service: "Bọc răng sứ",
    status: "booked",
  },
  {
    id: "a14",
    day: 4,
    start: "15:00",
    duration: 45,
    patient: "Hồ Ngọc Lan",
    service: "Điều trị nha chu",
    status: "booked",
  },
  {
    id: "a15",
    day: 5,
    start: "09:30",
    duration: 60,
    patient: "Tạ Quang Huy",
    service: "Nhổ răng khôn",
    status: "booked",
  },
];

export const initialAppts: Appt[] = rawAppts.map(({ day, ...rest }) => ({
  ...rest,
  date: toDateKey(addDays(weekAnchor, day)),
}));
